from textwrap import indent
from .schemas import TestSuite

HEADER = '''"""
Auto-generated by ai-testgen.
Edit safely: add concrete assertions for your app.
Run: pytest -q
"""
import pytest
'''

def _test_fn_name(tc_id: str, title: str) -> str:
    slug = "".join(ch.lower() if ch.isalnum() else "_" for ch in f"{tc_id}_{title}")
    while "__" in slug:
        slug = slug.replace("__", "_")
    return f"test_{slug.strip('_')}"[:80]

def render_pytest(suite: TestSuite) -> str:
    parts = [HEADER, f'# Feature: {suite.feature}\n']
    for case in suite.cases:
        fn = _test_fn_name(case.id, case.title)
        doc = f'{case.id} | {case.title} | Priority: {case.priority} | Tags: {", ".join(case.tags)}'
        body = ["# Preconditions:"] + [f"#  - {p}" for p in case.preconditions]
        body += ["# Steps:"] + [f"#  - ACTION: {s.action} | EXPECTED: {s.expected}" for s in case.steps]
        body += [
            "",
            "assert True  # TODO: replace with real assertions / API/UI calls",
        ]
        parts.append(f"def {fn}():\n    " + f'""" {doc} """\n' + indent("\n".join(body), "    ") + "\n")
    return "\n".join(parts)
